services:
  - type: web
    name: fastapi-ollama
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434
      - key: OLLAMA_BASE_URL
        value: http://127.0.0.1:11434   # talk to the in-container Ollama
    healthCheckPath: /healthz
